# Generated by Django 4.2.26 on 2025-11-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plans', to='plans.interesttag'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['start_time', 'is_active'], name='plans_start_t_268fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active'], name='plans_is_acti_85d1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['latitude', 'longitude'], name='plans_latitud_e530c7_idx'),
        ),
    ]
